@Restaurants.API_HostAddress = https://localhost:7034
@token = CfDJ8FNCtisP6UhBlVXdXUTLBU7xSDA1w0Lz6vhM1LnJYdi3eE4gaYIzSUheYUw0wm8LL6vYeMpTx9HJCh9-KDMI3p411jyF5vYqUKbjIF-ervxtiODve_HnhCZneKRLVxkm2Lq0S8pP52oDdwDyP7pRFFMZOxcvRLrcI26F8ORyKfltqICVYgxwz-WqvPK5HBCWRGIL7-5mUFoqv9LlVW_iiyrJFCVlXEbkfSE3buudmG1VWd3AG1lno7RU40agkxo3y07FJX4VitR-KTdTjsSEp7qIl333CSPp9nOrl3FPkl2Zh8unU27jpn9Y9fH5MTTgm0tgrq1DuZcEH_x2KI7n3-Ev6kTlWtie-XqHmS6mwq0gGKBklVZ-_NAMydQOE1jDEsunNtHA8nMh6vOhbbHlHk4UpPp6SbR9twztV4QYGlUxpEUjfhs1YdWQng8Ebjm_0V2xQzw5_dTjI68-ZyybpNgz31-TKcd0_d6PnLTQOmboCkzFNk3fBMA3Lrt3ikUR6k4BDfmr-NrCbw64VmArK_1PoM1ljjI6LJ1mdEkdYIumOEtdmde3KTk78MoFnE7o8liUS_FB3_3n4q070O4e0M4EtKyMzy9sRH04lEIb9jMxnJO45nY2BgtKtCKfYFv8g97FQ4piyFJeVjoNT3l7glO_g8GRGTWvnW6BLv_epMLrxQ-s7z6rjCjYFY3w7TOdFYyKVA0li2YwOkJ9Yc-Ap4ZpCAIJYK-Ke2PHhDJAUoK6sZbNtg6BVvcl_0jkYAxbcXJCc0MU1w9q7Z5WFQUVQVMjgspH3_pOKd0PyJn8xVIWeavgQaqjjJh7i0SR_Yd1iyZzNYeVc15aM2nZpERl0CFuhbIl1ImK8CL_7FU63M3AXpQNHoIfjDgwgt0iHot_rw


GET {{Restaurants.API_HostAddress}}/api/restaurants
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
      "Name": "Owner restaurant-1",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###


GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Authorization: Bearer {{token}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6
Authorization: Bearer {{token}}

### 

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "Owner2 restaurant2 - V1",
    "Description": "A cozy restaurant serving a variety of delicious dishes.",
    "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Dish 2",
  "description": "Dish 2 for Restaurant 1",
  "price": 10,
  "kiloCalories": 108,
  "restaurantId": 1
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/11
Authorization: Bearer {{token}}


###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user1@example.com",
    "password": "Sample@123$"
}

###

### testuser | owner | admin | user1

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@example.com",
    "password": "Sample@123$"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}

###
