@Restaurants.API_HostAddress = https://localhost:7034
@token = CfDJ8FNCtisP6UhBlVXdXUTLBU5El2oCNjmB90cup0P9wbZPOWXUjLPKuOCthZQNIjiXlPWwKqJ8UBwGsC8FEU-Kox7s623G5afKoBwKdMPpBL0uTwg5f78b1fl1rlnqim2D8raFgQ0cHUCJbCdp5vkabV_zopN2Fei_hhlUH5Fb37jj0Bzf4bN3FGcghhF_m44DGwmxe91yVL7cQYVD4auQaj3_hMf7bOsUX54OYYvs5y_xTtCPYYYyi6zr8AqgXnKcLggrtUeQQr7d6SJAW5lvL_E6CWUmYbxIbAg_bvg0Z17k1JJoqHcePG_zHeDn54iSe2e_7Axir7Kn6ueRZwk3FhUzKiQDOsut6Rg26Q4N6QiEs1rZeh1c0Majk7n-ziXhNlu8Jk5ZAlEhfLayfispmUs_vdxLdINhnigPyGMJM61HwwP53AnqXNiKgt6HIWaB11aZsUFTkk40C25YqjCzS8vgTqIoTb2kJq4co9rnCgNc4_hBa9BAl9021PgBQi3zeVlvwE_RcY0a5LQZa1TKQkfclstiMGLuvaHyQtk2lagQsVywpVThl-bbaQLdXY222coD1N6cpR7SMLU5MrWtYvQHK-UmGnqiYUlttmdOetCX5t7u_6rJSfKAtN1pwYPFcu_XBbevEne3C_IL_Ca7oyDwEk_4enC5ycZwDURS1Xuj5POkae-Umuviy9s5dDOVME7GcCUn57zmiuIMkLM6XFV2ivqONO1D0kZ876tg91GoOQSNcYZcRU9VxZHowSo_HtdY3-8Iygd6G514BfJDzIAEFhzUz45ItgqzpkChYW4T


GET {{Restaurants.API_HostAddress}}/api/restaurants
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
      "Name": "Owner New restaurant",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6
Authorization: Bearer {{token}}

### 

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "Owner2 restaurant2 - V1",
    "Description": "A cozy restaurant serving a variety of delicious dishes.",
    "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
  "name": "Dish 2",
  "description": "Dish 2 for Restaurant 1",
  "price": 10,
  "kiloCalories": 108,
  "restaurantId": 1
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/11



###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user1@example.com",
    "password": "Sample@123$"
}

###

### testuser | owner | admin | user1

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@example.com",
    "password": "Sample@123$"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}

###
