@Restaurants.API_HostAddress = https://localhost:7034
@token = CfDJ8FNCtisP6UhBlVXdXUTLBU7rb7l2iNi3o4eEePG2ZdoOoA1vmn0JuPJE1wogiG2nwdNmVXDdwzs2MHcYZRhcJYdQKVWDKM264DU_DIi6XNiOh7RcX2-OyuK77X5DMsRuJj_DOdD7asG_NgjBgqs-n9UxyIp5oFzsvLeXWmtRYrFMN2_0fvZsEO1mJbJ2szr-dCwlBtFRnTxPsm4McHFQh_Ymrb38J1qJYEKRH7t17rmzMpW--IbJi4SsMIYnyQBSgLJ22Mq8xT-uWlCTX52iD7s4g6K7pqXNM6wdPrAKi_pYfSKBMGkLntockHoYczW4pnhC-OULd4iL_79uy8__rEZaDnr4QpesrhbY6PUyV9DCHXh7rnEAsN9GC1qKypGQULUbkjeWRl5B8y0cqFBi95hsFpXY9qMVzkgXhSUzzNFk9on-6XzoPUACMr2PgaESZxsyGhiJVvTRpIqqwnxDLn-VQ48Az5wYNuvWX4z98RrqrPLS4H2Kvhl_S6HPRRruFbhNhe7Ib8R1IB2OBMDHY0Mfoyz_eZtAXUopWDXHYe3gOAa9VZfuiDuTv5GWwSqTffaIwQJvtCKSXNMX4_HpizJ-T3jPzVLesARivgLsGDTz0spXyCE4OA3Yegg3-LEB0uPcecmtAQy7uxT7N7yKIWpQ-spUBi-SsJt51bGxWk7sW9Npdw-2V1jqGpnk6gVWpw


GET {{Restaurants.API_HostAddress}}/api/restaurants
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1
Authorization: Bearer {{token}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
      "Name": "Owner New restaurant",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/6
Authorization: Bearer {{token}}

### 

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/3
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Name": "Owner2 restaurant2 - V1",
    "Description": "A cozy restaurant serving a variety of delicious dishes.",
    "HasDelivery": true
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
  "name": "Dish 2",
  "description": "Dish 2 for Restaurant 1",
  "price": 10,
  "kiloCalories": 108,
  "restaurantId": 1
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes/11



###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user1@example.com",
    "password": "Sample@123$"
}

###

### testuser | owner | admin | user1

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@example.com",
    "password": "Sample@123$"
}
###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality": "French",
  "DateOfBirth": "2010-01-01"
}

###


POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}

###
